### ISSUE TITLE
need to make executable explicit, and entry point

### ISSUE THREAD

**Issue by timruffles** [sidekickcode/tracker#29]
can't use shebangs, as needs to be absolute. so go for a executable and script to execute. have a few 'blessed' executables (e.g `ruby`, `node`) and possibility to absolute path.

``` toml
main="main.js"
bin="node"
```
